name: feiragreen_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  shared_preferences: '2.5.3'
  path: ^1.9.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  path_provider: ^2.0.14
  
  # SQLite dependencies
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

  # Firebase dependencies
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0
  firebase_auth_mocks: ^0.15.1
  fake_cloud_firestore: ^4.0.0
  get_it: ^8.2.0
  mocktail: ^1.0.4
  dartz: ^0.10.1

  local_auth: ^2.1.6
  go_router: ^16.2.4
  app_links: ^6.4.1
  logger: ^2.0.2+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagens/LogoFeiraGreen.png
    - assets/imagens/baners/imagem1.png
    - assets/imagens/baners/imagem2.png
    - assets/imagens/baners/imagem3.png
    - assets/imagens/product_images/
